version: '3'
services:
  stats:
    image: docker.io/bitnami/rabbitmq:3.9
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=e88285069
    ports:
      - '15672:15672'
      - '5672:5672'
    expose:
      - 5672
    volumes:
      - './data/rabbitmqstats_data:/bitnami'
  queue-disc1:
    image: docker.io/bitnami/rabbitmq:3.9
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@queue-disc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=e88285069
    volumes:
      - './data/rabbitmqdisc1_data:/bitnami'
  queue-ram1:
    image: docker.io/bitnami/rabbitmq:3.9
    environment:
      - RABBITMQ_NODE_TYPE=queue-ram
      - RABBITMQ_NODE_NAME=rabbit@queue-ram1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=e88285069
    volumes:
      - './data/rabbitmqram1_data:/bitnami'

volumes:
  rabbitmqstats_data:
    driver: local
  rabbitmqdisc1_data:
    driver: local
  rabbitmqram1_data:
    driver: local
