on:
  push:
    branches:
      - main

env:
  SECRET_MANAGER: dev/auth-api-stage
  ECR_REPOSITORY: auth-api-dev # Alterar para o nome do repo
  APP_NAME: auth-api # Alterar para o nome do APP
  CLUSTER_NAME: vobi-dev-eks # Alterar para o nome do cluster
  IMAGE_TAG: ${{ github.sha }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

name: Auth API DEVELOP

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}        
          node-version: 14
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install          
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            